### ISSUE TITLE
Differentiate between en and em dashes

### ISSUE THREAD

**Issue by timwilson** [mgmeyers/obsidian-smart-typography#1]
Please consider this a feature request.

I'd like to see `--` converted into an en dash (`&ndash;`) and `---` converted into an em dash (`&mdash;`). The two different dashes have different purposes, and it would be good to be able to use both.

Thanks for this plugin. I've been looking forward to this solution!

**Comment by Moonbase59** [comment]
I’m so happy I have all this on the keyboard … (Linux, but can be had on Windows, too).

**Comment by timwilson** [comment]
I just realized that typing `---` and converting to an em dash would be problematic if I'm trying to create a horizontal line in my Markdown document or defining the YAML front matter. Maybe there's another way.

@Moonbase59 Yes, I have key combinations for all of these typographical symbols on my Mac too. Having the plugin do some of these is really just a convenience for me.

**Comment by mgmeyers** [comment]
1.0.3 Should fix the issues here: Two dashes (--) will be converted to an en-dash (–). And en-dash followed by a dash will be converted to and em-dash (—). An em-dash followed by a dash will be converted into three dashes (---)
