### ISSUE TITLE
Allow plugin settings to govern dash behavior

### ISSUE THREAD

**Issue by KutuzovGambit** [mgmeyers/obsidian-smart-typography#10]
A lot of people only use em-dash rather than en-dash, and most software including macOS converts two dashes to an em-dash rather than an en-dash. Please create a settings option to govern behavior so that those wishing to go with the more commonplace usage of two dashes to an em-dash can do so. Thanks for the great plugin!

**Comment by mgmeyers** [comment]
Hi @KutuzovGambit the logic for dashes is like so:

Two dashes for en dash
Three dashes for em dash
Four dashes for three normal dashes (eg, `---`)

I'll think about adding a setting to skip the en dash, though. Let me see how complex that would be and get back to you.

**Comment by mgmeyers** [comment]
Ok, I've added a setting to skip en-dashes. This will only work with the latest insider build, though. Everyone should have access once live preview is released to the public.

<img width="715" alt="Screen Shot 2021-12-12 at 1 36 10 PM" src="https://user-images.githubusercontent.com/2694747/145730488-bdfbc141-3a2a-4a6b-b712-b3b77c8058a2.png">

**Comment by KutuzovGambit** [comment]
> Ok, I've added a setting to skip en-dashes. This will only work with the latest insider build, though. Everyone should have access once live preview is released to the public.
> 
> <img alt="Screen Shot 2021-12-12 at 1 36 10 PM" width="715" src="https://user-images.githubusercontent.com/2694747/145730488-bdfbc141-3a2a-4a6b-b712-b3b77c8058a2.png">

Wonderful, thank you!!
