### ISSUE TITLE
Way to turn it off within a word? E.g. "didn't", "isn't"?

### ISSUE THREAD

**Issue by ReaderGuy42** [mgmeyers/obsidian-smart-typography#11]
Is there a way to have the single quotation marks not become the fancy curly quote if it's used as an apostrophe within a word?

The reason is that the spell checker doesn't recognize stuff like "didn" or "isn" since the curly quote separates the thing after it.

Thanks!

**Comment by jamiekowalski** [comment]
@ReaderGuy42 If you're using a Mac (I'm not sure about Windows or Linux), it appears this issue has been resolved as of [Obsidian v0.13.7](https://forum.obsidian.md/t/obsidian-release-v0-13-7-insider-build/28061), which switched to using the native spell-checker.

**Comment by ReaderGuy42** [comment]
Thanks, I'm not on a Mac. But I think (not sure) this is solved in the new Live Preview version of the new spell check.

**Comment by mgmeyers** [comment]
Can confirm that the new obsidian spellchecker fixes this issue
