### ISSUE TITLE
Live preview in Obsidian beta breaks this plugin 

### ISSUE THREAD

**Issue by seatrout** [mgmeyers/obsidian-smart-typography#13]
Using the latest Obsidian insider release (0.13.7) with the experimental live feature turned this plugin stops working entirely, whether or not the WYSIWYG view is operating. Only turning that feature right off restores functionality.

I have only tested/tripped over this issue on Windows but I expect to find it everywhere.

**Comment by peterkehlerjr** [comment]
Same here for Linux using insider release v0.13.8

**Comment by mgmeyers** [comment]
@seatrout and @peterkehlerjr Live preview and the new source mode are now supported. There are a few minor bugs to work out, but it should be mostly working. Let me know if you have any issues with it.

**Comment by peterkehlerjr** [comment]
thx @mgmeyers
