### ISSUE TITLE
Support for fractions.

### ISSUE THREAD

**Issue by gluecode** [mgmeyers/obsidian-smart-typography#17]
I note that the plugin supports fractions. But in the current version of Obsidian (v0.12.19) and the plugin (1.0.8), fractions do not seem to be supported. I tested in editor and preview modes.

<img width="692" alt="IMG 2021-12-18 at 12 25 54@2x" src="https://user-images.githubusercontent.com/15410/146654693-65d66f99-5486-425b-8b47-e5ecd2829c31.png">
.

**Comment by mgmeyers** [comment]
@gluecode Fractions are only supported in obsidian version 0.13.8, so you'll have to wait until the next public release for access to these.
