### ISSUE TITLE
Plugin should not replease text in #tags 

### ISSUE THREAD

**Issue by dariuszkowalski-com** [mgmeyers/obsidian-smart-typography#18]
When I turn this option on
![image](https://user-images.githubusercontent.com/37656900/148747395-cdb9785e-b15c-44e7-8a6b-a3928d2998b2.png)

`#22/01/10`  will be changed to
![image](https://user-images.githubusercontent.com/37656900/148747647-525441b1-1983-40e4-9379-4768941a3d0d.png)

It shouldn't parse tags at all.

**Comment by mgmeyers** [comment]
@dariuszkowalski-com This should be fixed now. Let me know if you run into any issues
