### ISSUE TITLE
[Feature Request] Allow smart quotes to know when you are writing in ``` dataview 

### ISSUE THREAD

**Issue by Obadiahcruz** [mgmeyers/obsidian-smart-typography#2]
you cannot easily write scripts with the smart quotes because dataview does not recognize them.

**Comment by Mara-Li** [comment]
Same problem with templater. With the new update, I think it's possible to know if we are in a templater script or no (between <% and %>)
Maybe using a regex can work too.

**Comment by mgmeyers** [comment]
This has been fixed in 1.0.4!
