### ISSUE TITLE
Don't autoclose quotes after punctuation

### ISSUE THREAD

**Issue by oldjove** [mgmeyers/obsidian-smart-typography#20]
Seems that the plugin behaves differently if you type a quotation mark after a letter or after punctuation. After a letter only a single closing quotation mark is created -- the correct behaviour -- but after punctuation you get a new pair. So if I want to add a quotation mark after "Hello! , I'll instead get a pair. I find that there are plenty of situations where this happens and I'd like it if typing a quotation mark after *any* other symbol didn't trigger the autoclose function. Does that make sense?

**Comment by mgmeyers** [comment]
@oldjove So I finally had some time to check this out, and it's actually a bug with Obsidian. If you turn off smart typography, you'll get a pair of quotes after punctuation. Maybe file a bug in the obsidian forums?

**Comment by oldjove** [comment]
@mgmeyers Thanks! I hadn't noticed this on native Obsidian. I think it only struck me with Smart Typography because of the extra keystrokes needed to get things right - i.e. normally a single 'delete' is sufficient but with ST more mucking around is involved to get the correct quotation mark in place. I'll open a bug report on the forum.
