### ISSUE TITLE
Guillemets and non-breaking spaces

### ISSUE THREAD

**Issue by KelsoUxlay** [mgmeyers/obsidian-smart-typography#21]
In French, a pair of guillemets requires a non-breaking space following the opening guillemet and a non-breaking space preceding the closing guillemet («  »). This is to prevent an automatic line break at the position of the white space. On a windows keyboard, a non-breaking space can be produced by typing 0160 on the numeric keypad while pressing down the Alt key. For me, ideally, opening a guillemet with `<<` (or with « ) should automaticallly create the guillemet pair, insert 2 non-breaking spaces between the guillemets and position the cursor between the two non-breaking spaces, ready to insert text. In the following example, the cursor should be at the position of the vertical bar : « | » (I have added the vertical bar in the example only to show where the cursor should be located).

**Comment by mgmeyers** [comment]
@KelsoUxlay Thanks for letting me know! I've added non breaking spaces like you suggested. Let me know if this works as you'd expect.

**Comment by KelsoUxlay** [comment]
Hello Matthew - Thanks for getting back to me.  I have installed the update and restarted Obsidian. May be, the plugin is interfering with another plugin.  If I type <<, the two caracters are converted to «, but I see no spaces, and the closing pair does not appear. If I add the closing >> manually, they are converted to », but no spaces are inserted; I end up with «». If I insert regular spaces and type something inbetween, the spaces are not converted to non-breaking spaces either

**Comment by mgmeyers** [comment]
Hmm, just to check, are you on version 1.0.16 of the plugin? Here's what it looks like for me:

https://user-images.githubusercontent.com/2694747/160939472-1b3c3de7-ba46-4407-96d0-dd8b03392ec9.mov

**Comment by KelsoUxlay** [comment]
I confirm  1.0.16 but yes, I use Legacy; I will change the setting

**Comment by KelsoUxlay** [comment]
Now it work as exepected - Real cool - Thanks a lot for the good work

**Comment by mgmeyers** [comment]
@KelsoUxlay Just FYI, I've changed back to not including the space by default, but made guillemets configurable so users can add the space if they'd like:

<img width="774" alt="Screen Shot 2022-04-24 at 4 46 02 PM" src="https://user-images.githubusercontent.com/2694747/165001697-433fb7c9-a344-4d73-bb73-3cf89955c272.png">

**Comment by KelsoUxlay** [comment]
Excellent!

That works well for me

The best of both worlds

 

KU-)

 

De : Matthew Meyers ***@***.***> 
Envoyé : 24 avril 2022 19:48
À : mgmeyers/obsidian-smart-typography ***@***.***>
Cc : KelsoUxlay ***@***.***>; Mention ***@***.***>
Objet : Re: [mgmeyers/obsidian-smart-typography] Guillemets and non-breaking spaces (Issue #21)

 

@KelsoUxlay <https://github.com/KelsoUxlay>  Just FYI, I've changed back to not including the space by default, but made guillemets configurable so users can add the space if they'd like:

 <https://user-images.githubusercontent.com/2694747/165001697-433fb7c9-a344-4d73-bb73-3cf89955c272.png>
