### ISSUE TITLE
Spaces around guillemets intentional?

### ISSUE THREAD

**Issue by PeteMichaud** [mgmeyers/obsidian-smart-typography#23]
The replacement logic for "<<" puts a space after the character, while the logic for ">>" puts a space before the character. This isn't how quote characters generally work, eg. 

`«This is a quote»`

vs

`« This is a quote with spaces for some reason »`

I think the logic should produce the first one, not the second one?

**Comment by mgmeyers** [comment]
@PeteMichaud This was a change I added in response to this issue: https://github.com/mgmeyers/obsidian-smart-typography/issues/21

I'm unfamiliar with how guillemets work, but to make things flexible, I've added a setting to control the output of a guillemet:

<img width="774" alt="Screen Shot 2022-04-24 at 4 46 02 PM" src="https://user-images.githubusercontent.com/2694747/165001697-433fb7c9-a344-4d73-bb73-3cf89955c272.png">

It will now default to no spaces. Let me know if you run into any issues with this.

**Comment by PeteMichaud** [comment]
Great, thanks so much! I think providing the option is the right move—the many different languages that use the marks all have different rules, so there are valid use cases both with and without the spaces.
