### ISSUE TITLE
Skip en-dash doesn't work

### ISSUE THREAD

**Issue by TheEnquirer** [mgmeyers/obsidian-smart-typography#24]
Hi! Love the plugin, it's super helpful. 

I've been using it for a bit, and it seems that regardless of whether or not the `Skip en-dash` option is checked, two dashes will be converted to an en-dash and three will be converted to an em-dash. 

The `Skip en-dash` feature would be super helpful, but unfortunately it doesn't seem to be working. 

Thanks!

**Comment by mgmeyers** [comment]
Hmm, the setting seems to work ok on my end. Here's a video of a manually typed em dash, smart typography em dash (with skip en-dash on), and a manually typed en dash.

https://user-images.githubusercontent.com/2694747/165386478-170dc23f-2262-4564-9cc0-722bb02a15d4.mov

**Comment by TheEnquirer** [comment]
How strange! Here's a video of what's happening on my end:

https://user-images.githubusercontent.com/55263795/165388052-793328ba-a775-4e3e-81a1-dd3ceb554abb.mov

**Comment by mgmeyers** [comment]
Hmm, strange indeed. Are you using the legacy editor, or the new one? Also, it looks like you may be using the vim plugin. Is that right?

**Comment by TheEnquirer** [comment]
Ah, yes. Vim doesn't seem to be affecting it, but disabling the legacy editor does make it work.
