### ISSUE TITLE
[Feature Request] Use same method of Custom Icons to allow custom arrow

### ISSUE THREAD

**Issue by Obadiahcruz** [mgmeyers/obsidian-smart-typography#3]
I have a certain arrow that alfred recognizes and allows it to be used in any editor. Can there be a way to override the current arrow used and use ➞ ?

Feature Request because this will allow to use same arrow even if i change fonts.

**Comment by mgmeyers** [comment]
@Obadiahcruz, you can now customize the arrow characters. Your font will still need to support whatever arrow character you choose, however.
