### ISSUE TITLE
Can the dashes setting be ignored on the first line of a note, so that frontmatter formatting can be typed in?

### ISSUE THREAD

**Issue by YousufSSyed** [mgmeyers/obsidian-smart-typography#45]
Frontmatter is defined by `---` on the top and bottom lines with text in between. Its more tedious to have to press backspace after typing in the first two dashes. I could turn it off, but instead I made a Templater template to insert frontmatter.

**Comment by mgmeyers** [comment]
@YousufSSyed Typing 4 dashes in a row will revert the output to `---`. You can shorten it to three by turning on the `Skip en-dash` setting.

<img width="643" alt="Screenshot 2023-04-17 at 6 35 10 PM" src="https://user-images.githubusercontent.com/2694747/232646739-c8cf7296-7f63-498e-a873-7cf23a8d0e78.png">
