### ISSUE TITLE
Frontmatter with em-dashes

### ISSUE THREAD

**Issue by memee** [mgmeyers/obsidian-smart-typography#49]
How to have em-dashes convertion while being able to create Frontmatter block?

**Comment by mgmeyers** [comment]
Hi @memee, by default, an em-dash followed by a dash will result in `---`

<img width="785" alt="Screenshot 2023-08-28 at 9 25 50 AM" src="https://github.com/mgmeyers/obsidian-smart-typography/assets/2694747/e6159128-2c65-4443-8f78-17da8e50f6c4">

**Comment by memee** [comment]
Thank you. Indeed. Sorry for the trouble
