### ISSUE TITLE
Support for non-English languages

### ISSUE THREAD

**Issue by ottsch** [mgmeyers/obsidian-smart-typography#5]
Quotes and dashes are displayed differently for different languages. Would be cool to have a setting for the actual characters used.

**Comment by ottsch** [comment]
For German it would be 
- „“ or » « or « » 
- ‚ ‘ or › ‹ or ‹ ›
- n-dashes

**Comment by kithairon** [comment]
For French this would be:
• ’ and ' (the latter for Breton)
• « » and ‹ › as apostrophies
• tiret long « — »  = Unicode U+2014 HTML &mdash
• tiret moyen / demi‑tiret  « – » = Unicode U+2013 HTML &ndash
• tiret court ou « trait d’union » « - » = Unicode U+002D, HTML &#x002D;

**Comment by TheHolyDenier** [comment]
Ey! Very appreciate this plugin, it makes typing easier 😁 

In Spanish: 
- «» as quotes 
- » to open some paragraphs

That, with your other conversions (double and single quotes, mdash and ellipsis, we use all of them), would let us settled and ready to go 😋 Thank you.

**Comment by mgmeyers** [comment]
Hey all! You can now customize which characters are used for quotes:

<img width="772" alt="Screen Shot 2021-06-29 at 11 47 13 AM" src="https://user-images.githubusercontent.com/2694747/123851182-c16e6700-d8cf-11eb-96ef-5a039d04e906.png">

There's also an option to convert double angle brackets to guillemets (turned off by default):

<img width="759" alt="Screen Shot 2021-06-29 at 11 47 53 AM" src="https://user-images.githubusercontent.com/2694747/123851281-d945eb00-d8cf-11eb-93c2-66a973e51382.png">

Let me know if there are any improvements I can make here.
