### ISSUE TITLE
Problem with HTML comments

### ISSUE THREAD

**Issue by memee** [mgmeyers/obsidian-smart-typography#55]
When I type 4 times "-", I get "---" as expected.
If I type ">" after that, I get a string "--→". It should be "--->".
I think it should respect HTML comments like ""

**Comment by sevmonster** [comment]
[HTML comments are `<!--`](https://html.spec.whatwg.org/multipage/parsing.html#markup-declaration-open-state), the third dash will be simply part of the comment.

You can either hit backspace to undo the conversion, or use [`%%Obsidian comments%%`](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Comments), which are much easier to type and serve the same purpose.
