### ISSUE TITLE
An easier way to make horizontal rules

### ISSUE THREAD

**Issue by thorinii** [mgmeyers/obsidian-smart-typography#6]
I have the em-dash feature turned on (I love it), but it makes it a bit difficult to type `---` horizontal rules.

Is there a way to have a `--` turn into an em dash, but then another dash turn it back again? Is it possible to set up a match rule to do this?

If #1 gets implemented, then this would have to be disabled.

**Comment by mgmeyers** [comment]
Thanks @thorinii! This has been added in 1.0.3: Two dashes (--) will be converted to an en-dash (–). And en-dash followed by a dash will be converted to and em-dash (—). An em-dash followed by a dash will be converted into three dashes (---).

**Comment by thorinii** [comment]
Ah, that makes sense. Thanks a lot!
