### ISSUE TITLE
Support mobile apps

### ISSUE THREAD

**Issue by laurentlbm** [mgmeyers/obsidian-smart-typography#7]
Title says it all.

**Comment by mgmeyers** [comment]
@laurentlbm Just a heads up, once the next version of obsidian for mobile is released, this plugin should work on mobile.

**Comment by laurentlbm** [comment]
That's fantastic, I'm looking forward to it. Thanks!

**Comment by Calorion** [comment]
It doesn't. It still says "This plugin does not support your device." 

It's very frustrating that this plugin is even needed on iPad; the system settings should do this for you. But apparently not.

**Comment by mgmeyers** [comment]
Forgot to update this issue, but smart typography now works on mobile!

**Comment by laurentlbm** [comment]
Thank you! 

Now I just need this systemwide on my phone and tablet... 🤔
