### ISSUE TITLE
curly and straight quotes not interchangeable in links, unlinked mentions

### ISSUE THREAD

**Issue by oldjove** [mgmeyers/obsidian-smart-typography#8]
Creating a link in a note using a curly quote will not find the target file if the target's title has a straight quote. Similarly, the new note won't show up in the unlinked mentions of the original note.

E.g. if the note _Luhmann's method_ (with straight quote) exists, trying to link with _Luhmann's method_ (with smart quote) will not find it.

I think that for the purpose of searching, straight and curly quotes should be interchangeable.

**Comment by mgmeyers** [comment]
@oldjove Unfortunately, this isn't something I can control on my end. All this plugin does is swap out characters as you type. Modifying search behavior would need to be a feature request for Obsidian.

**Comment by oldjove** [comment]
@mgmeyers Ah, okay. Thanks for the clarification.
